version: 0.2
 
env:
  variables:
    ACTION: "plan"   # default (will override in pipeline)
 
phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
 
  pre_build:
    commands:
      - echo "Terraform Init"
      - terraform init
 
  build:
    commands:
      - echo "Action is $ACTION"
 
      - |
        if [ "$ACTION" = "plan" ]; then
          echo "Running Terraform Plan"
          terraform plan -out=tfplan
 
        elif [ "$ACTION" = "apply" ]; then
          echo "Running Terraform Apply"
          terraform apply -auto-approve
 
        else
          echo "Invalid ACTION"
          exit 1
        fi
 
artifacts:
  files:
    - '**/*'
